[package]
name = "idtk"
version = "0.1.0"
edition = "2024"

[dependencies]
fast32 = { version = "1.0", optional = true }
ring = "0.17"
thiserror = "2"
time = "0.3"

[features]
base32 = ["dep:fast32"]
base64 = ["dep:fast32"]
