name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests w. base32
      run: cargo test --features base32 --verbose
    - name: Run tests w. base64
      run: cargo test --features base64 --verbose
    - name: Run tests
      run: cargo test --verbose
